version: '3.8'
services:
  ms-clientes-personas:
    build:
      context: ./ms-clientes-personas
      dockerfile: Dockerfile    
    ports:
      - "8081:8081"
    env_file: .env
    depends_on:
      - rabbitmq
      - postgres

  ms-cuentas-movimientos:
    build:
      context: ./ms-cuentas-movimientos
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file: .env
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672" 
    env_file: .env

  postgres:
    image: postgres:14
    container_name: postgres
    env_file: .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql:ro

volumes:
  postgres_data:
